### ISSUE TITLE
In DC-iOS it is not possible to access a bot via app

### ISSUE THREAD

**Issue by Raiden-GH** [deltachat-bot/public-bots#4] opened 2024-01-06 13:35 UTC
In DC-iOS 1.42.8 it is not possible to call a bot via the bot app. 
The chat cannot be opened even by tapping the link several times. Nothing happens. 
The problem does not exist in DC-Desktop and DC-Android.

**Comment by adbenitez** [comment] 2024-02-02 17:23
hi, sorry for the late reply, the problem is that DC in iOS doesn't support opening the kind of link that is used for contact verification in DC

**Comment by adbenitez** [comment] 2024-06-20 15:17
recent DC iOS version already support the bot links (fixed in https://github.com/deltachat/deltachat-ios/pull/2158)

**Closed by adbenitez** 2024-06-20 15:17 UTC
